---

- import_tasks: rhacs-operator.yml
  when: rhacs_operator | bool

- import_tasks: central.yml
  when: central | bool

- import_tasks: secured-cluster.yml
  when: secured_cluster | bool
  
- import_tasks: roxctl.yml
  when: roxctl | bool
  
- import_tasks: delete_secured_cluster.yml
  when: delete_secured_cluster | bool
