---

- name: Wait for central pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: stackrox
    wait: yes
    wait_sleep: 10
    
- name: Get Central route
  shell: "oc get route central -n stackrox -o jsonpath='{ .spec.host }'"
  register: central_url

- name: Get Central admin password
  shell: "oc get secret central-htpasswd -n stackrox -o jsonpath='{ .data.password }' | base64 -d"
  register: central_password
  
- name: Generate init-bundle secrets file
  shell: curl -sk -X POST -u admin:{{ central_password.stdout }} https://{{ central_url.stdout }}/v1/cluster-init/init-bundles -d '{"name":"init_bundle"}' | jq -r ".kubectlBundle" | base64 -d
  register: init_bundle
  
- name: Echo init_bundle contents into cluster_init_bundle.yaml
  copy:
    content: "{{ init_bundle.stdout }}"
    dest: ~/cluster_init_bundle.yaml
  
- name: Create init bundle secrets
  kubernetes.core.k8s:
    state: present
    namespace: stackrox
    src: ~/cluster_init_bundle.yaml

- name: Create secured cluster
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: platform.stackrox.io/v1alpha1
      kind: SecuredCluster
      metadata:
        name: stackrox-secured-cluster-services
        namespace: stackrox
      spec:
        admissionControl:
          bypass: BreakGlassAnnotation
          contactImageScanners: DoNotScanInline
          listenOnCreates: true
          listenOnEvents: true
          listenOnUpdates: true
          timeoutSeconds: 20
        auditLogs:
          collection: Auto
        centralEndpoint: '{{ central_url.stdout }}:443'
        clusterName: '{{ cluster_name }}'
        perNode:
          collector:
            collection: EBPF
            imageFlavor: Regular
          taintToleration: TolerateTaints
        scanner:
          analyzer:
            scaling:
              autoScaling: Enabled
              maxReplicas: 5
              minReplicas: 2
              replicas: 3
          scannerComponent: AutoSense

# The secrets generated from this file can't be used for other Secured Clusters
# If another Secured Cluster need to be created, regenerate this file
- name: Remove cluster-init-bundle.yaml
  file:
    path: ~/cluster_init_bundle.yaml
    state: absent


